[application]

[web.app]
base_path = "Personal-Site"

# HTML title tag content
title = "Jonah Irizarry"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

[web.watcher]
index_on_404 = true

# Javascript code file
# serve: [dev-server] only
script = []
